### ISSUE TITLE
Safari: content not going around the portrait featured image

### ISSUE THREAD

**Issue by cristianfrumusanu** [pixelgrade/patch#192]
![image](https://user-images.githubusercontent.com/5011858/27126101-15859eba-50ff-11e7-8d5b-41b5498437d8.png)

solutie (de testat, totusi):

```css
.single .entry-header,
.page:not(.entry-card) .entry-header {
	overflow: visible;
}

.single .entry-header .entry-meta, 
.page:not(.entry-card) .entry-header .entry-meta {
	overflow: hidden;
}
```
